package main

type opcodeInformation struct {
	mnemonic string
	operands []operand
}

type operand struct {
	name      string
	immediate bool
}

func reg(name string) operand {
	return operand{name, false}
}

func imm(name string) operand {
	return operand{name, true}
}

// opcodeInfo provides a string representation of every opcode, used by the debugger.
var opcodeInfo = []opcodeInformation{
	{"NOP", []operand{}},
	{"LD", []operand{imm("BC"), imm("n16")}},
	{"LD", []operand{reg("BC"), imm("A")}},
	{"INC", []operand{imm("BC")}},
	{"INC", []operand{imm("B")}},
	{"DEC", []operand{imm("B")}},
	{"LD", []operand{imm("B"), imm("n8")}},
	{"RLCA", []operand{}},
	{"LD", []operand{reg("a16"), imm("SP")}},
	{"ADD", []operand{imm("HL"), imm("BC")}},
	{"LD", []operand{imm("A"), reg("BC")}},
	{"DEC", []operand{imm("BC")}},
	{"INC", []operand{imm("C")}},
	{"DEC", []operand{imm("C")}},
	{"LD", []operand{imm("C"), imm("n8")}},
	{"RRCA", []operand{}},
	{"STOP", []operand{imm("n8")}},
	{"LD", []operand{imm("DE"), imm("n16")}},
	{"LD", []operand{reg("DE"), imm("A")}},
	{"INC", []operand{imm("DE")}},
	{"INC", []operand{imm("D")}},
	{"DEC", []operand{imm("D")}},
	{"LD", []operand{imm("D"), imm("n8")}},
	{"RLA", []operand{}},
	{"JR", []operand{imm("e8")}},
	{"ADD", []operand{imm("HL"), imm("DE")}},
	{"LD", []operand{imm("A"), reg("DE")}},
	{"DEC", []operand{imm("DE")}},
	{"INC", []operand{imm("E")}},
	{"DEC", []operand{imm("E")}},
	{"LD", []operand{imm("E"), imm("n8")}},
	{"RRA", []operand{}},
	{"JR", []operand{imm("NZ"), imm("e8")}},
	{"LD", []operand{imm("HL"), imm("n16")}},
	{"LD", []operand{reg("HL+"), imm("A")}},
	{"INC", []operand{imm("HL")}},
	{"INC", []operand{imm("H")}},
	{"DEC", []operand{imm("H")}},
	{"LD", []operand{imm("H"), imm("n8")}},
	{"DAA", []operand{}},
	{"JR", []operand{imm("Z"), imm("e8")}},
	{"ADD", []operand{imm("HL"), imm("HL")}},
	{"LD", []operand{imm("A"), reg("HL+")}},
	{"DEC", []operand{imm("HL")}},
	{"INC", []operand{imm("L")}},
	{"DEC", []operand{imm("L")}},
	{"LD", []operand{imm("L"), imm("n8")}},
	{"CPL", []operand{}},
	{"JR", []operand{imm("NC"), imm("e8")}},
	{"LD", []operand{imm("SP"), imm("n16")}},
	{"LD", []operand{reg("HL-"), imm("A")}},
	{"INC", []operand{imm("SP")}},
	{"INC", []operand{reg("HL")}},
	{"DEC", []operand{reg("HL")}},
	{"LD", []operand{reg("HL"), imm("n8")}},
	{"SCF", []operand{}},
	{"JR", []operand{imm("C"), imm("e8")}},
	{"ADD", []operand{imm("HL"), imm("SP")}},
	{"LD", []operand{imm("A"), reg("HL-")}},
	{"DEC", []operand{imm("SP")}},
	{"INC", []operand{imm("A")}},
	{"DEC", []operand{imm("A")}},
	{"LD", []operand{imm("A"), imm("n8")}},
	{"CCF", []operand{}},
	{"LD", []operand{imm("B"), imm("B")}},
	{"LD", []operand{imm("B"), imm("C")}},
	{"LD", []operand{imm("B"), imm("D")}},
	{"LD", []operand{imm("B"), imm("E")}},
	{"LD", []operand{imm("B"), imm("H")}},
	{"LD", []operand{imm("B"), imm("L")}},
	{"LD", []operand{imm("B"), reg("HL")}},
	{"LD", []operand{imm("B"), imm("A")}},
	{"LD", []operand{imm("C"), imm("B")}},
	{"LD", []operand{imm("C"), imm("C")}},
	{"LD", []operand{imm("C"), imm("D")}},
	{"LD", []operand{imm("C"), imm("E")}},
	{"LD", []operand{imm("C"), imm("H")}},
	{"LD", []operand{imm("C"), imm("L")}},
	{"LD", []operand{imm("C"), reg("HL")}},
	{"LD", []operand{imm("C"), imm("A")}},
	{"LD", []operand{imm("D"), imm("B")}},
	{"LD", []operand{imm("D"), imm("C")}},
	{"LD", []operand{imm("D"), imm("D")}},
	{"LD", []operand{imm("D"), imm("E")}},
	{"LD", []operand{imm("D"), imm("H")}},
	{"LD", []operand{imm("D"), imm("L")}},
	{"LD", []operand{imm("D"), reg("HL")}},
	{"LD", []operand{imm("D"), imm("A")}},
	{"LD", []operand{imm("E"), imm("B")}},
	{"LD", []operand{imm("E"), imm("C")}},
	{"LD", []operand{imm("E"), imm("D")}},
	{"LD", []operand{imm("E"), imm("E")}},
	{"LD", []operand{imm("E"), imm("H")}},
	{"LD", []operand{imm("E"), imm("L")}},
	{"LD", []operand{imm("E"), reg("HL")}},
	{"LD", []operand{imm("E"), imm("A")}},
	{"LD", []operand{imm("H"), imm("B")}},
	{"LD", []operand{imm("H"), imm("C")}},
	{"LD", []operand{imm("H"), imm("D")}},
	{"LD", []operand{imm("H"), imm("E")}},
	{"LD", []operand{imm("H"), imm("H")}},
	{"LD", []operand{imm("H"), imm("L")}},
	{"LD", []operand{imm("H"), reg("HL")}},
	{"LD", []operand{imm("H"), imm("A")}},
	{"LD", []operand{imm("L"), imm("B")}},
	{"LD", []operand{imm("L"), imm("C")}},
	{"LD", []operand{imm("L"), imm("D")}},
	{"LD", []operand{imm("L"), imm("E")}},
	{"LD", []operand{imm("L"), imm("H")}},
	{"LD", []operand{imm("L"), imm("L")}},
	{"LD", []operand{imm("L"), reg("HL")}},
	{"LD", []operand{imm("L"), imm("A")}},
	{"LD", []operand{reg("HL"), imm("B")}},
	{"LD", []operand{reg("HL"), imm("C")}},
	{"LD", []operand{reg("HL"), imm("D")}},
	{"LD", []operand{reg("HL"), imm("E")}},
	{"LD", []operand{reg("HL"), imm("H")}},
	{"LD", []operand{reg("HL"), imm("L")}},
	{"HALT", []operand{}},
	{"LD", []operand{reg("HL"), imm("A")}},
	{"LD", []operand{imm("A"), imm("B")}},
	{"LD", []operand{imm("A"), imm("C")}},
	{"LD", []operand{imm("A"), imm("D")}},
	{"LD", []operand{imm("A"), imm("E")}},
	{"LD", []operand{imm("A"), imm("H")}},
	{"LD", []operand{imm("A"), imm("L")}},
	{"LD", []operand{imm("A"), reg("HL")}},
	{"LD", []operand{imm("A"), imm("A")}},
	{"ADD", []operand{imm("A"), imm("B")}},
	{"ADD", []operand{imm("A"), imm("C")}},
	{"ADD", []operand{imm("A"), imm("D")}},
	{"ADD", []operand{imm("A"), imm("E")}},
	{"ADD", []operand{imm("A"), imm("H")}},
	{"ADD", []operand{imm("A"), imm("L")}},
	{"ADD", []operand{imm("A"), reg("HL")}},
	{"ADD", []operand{imm("A"), imm("A")}},
	{"ADC", []operand{imm("A"), imm("B")}},
	{"ADC", []operand{imm("A"), imm("C")}},
	{"ADC", []operand{imm("A"), imm("D")}},
	{"ADC", []operand{imm("A"), imm("E")}},
	{"ADC", []operand{imm("A"), imm("H")}},
	{"ADC", []operand{imm("A"), imm("L")}},
	{"ADC", []operand{imm("A"), reg("HL")}},
	{"ADC", []operand{imm("A"), imm("A")}},
	{"SUB", []operand{imm("A"), imm("B")}},
	{"SUB", []operand{imm("A"), imm("C")}},
	{"SUB", []operand{imm("A"), imm("D")}},
	{"SUB", []operand{imm("A"), imm("E")}},
	{"SUB", []operand{imm("A"), imm("H")}},
	{"SUB", []operand{imm("A"), imm("L")}},
	{"SUB", []operand{imm("A"), reg("HL")}},
	{"SUB", []operand{imm("A"), imm("A")}},
	{"SBC", []operand{imm("A"), imm("B")}},
	{"SBC", []operand{imm("A"), imm("C")}},
	{"SBC", []operand{imm("A"), imm("D")}},
	{"SBC", []operand{imm("A"), imm("E")}},
	{"SBC", []operand{imm("A"), imm("H")}},
	{"SBC", []operand{imm("A"), imm("L")}},
	{"SBC", []operand{imm("A"), reg("HL")}},
	{"SBC", []operand{imm("A"), imm("A")}},
	{"AND", []operand{imm("A"), imm("B")}},
	{"AND", []operand{imm("A"), imm("C")}},
	{"AND", []operand{imm("A"), imm("D")}},
	{"AND", []operand{imm("A"), imm("E")}},
	{"AND", []operand{imm("A"), imm("H")}},
	{"AND", []operand{imm("A"), imm("L")}},
	{"AND", []operand{imm("A"), reg("HL")}},
	{"AND", []operand{imm("A"), imm("A")}},
	{"XOR", []operand{imm("A"), imm("B")}},
	{"XOR", []operand{imm("A"), imm("C")}},
	{"XOR", []operand{imm("A"), imm("D")}},
	{"XOR", []operand{imm("A"), imm("E")}},
	{"XOR", []operand{imm("A"), imm("H")}},
	{"XOR", []operand{imm("A"), imm("L")}},
	{"XOR", []operand{imm("A"), reg("HL")}},
	{"XOR", []operand{imm("A"), imm("A")}},
	{"OR", []operand{imm("A"), imm("B")}},
	{"OR", []operand{imm("A"), imm("C")}},
	{"OR", []operand{imm("A"), imm("D")}},
	{"OR", []operand{imm("A"), imm("E")}},
	{"OR", []operand{imm("A"), imm("H")}},
	{"OR", []operand{imm("A"), imm("L")}},
	{"OR", []operand{imm("A"), reg("HL")}},
	{"OR", []operand{imm("A"), imm("A")}},
	{"CP", []operand{imm("A"), imm("B")}},
	{"CP", []operand{imm("A"), imm("C")}},
	{"CP", []operand{imm("A"), imm("D")}},
	{"CP", []operand{imm("A"), imm("E")}},
	{"CP", []operand{imm("A"), imm("H")}},
	{"CP", []operand{imm("A"), imm("L")}},
	{"CP", []operand{imm("A"), reg("HL")}},
	{"CP", []operand{imm("A"), imm("A")}},
	{"RET", []operand{imm("NZ")}},
	{"POP", []operand{imm("BC")}},
	{"JP", []operand{imm("NZ"), imm("a16")}},
	{"JP", []operand{imm("a16")}},
	{"CALL", []operand{imm("NZ"), imm("a16")}},
	{"PUSH", []operand{imm("BC")}},
	{"ADD", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$00")}},
	{"RET", []operand{imm("Z")}},
	{"RET", []operand{}},
	{"JP", []operand{imm("Z"), imm("a16")}},
	{"PREFIX", []operand{}},
	{"CALL", []operand{imm("Z"), imm("a16")}},
	{"CALL", []operand{imm("a16")}},
	{"ADC", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$08")}},
	{"RET", []operand{imm("NC")}},
	{"POP", []operand{imm("DE")}},
	{"JP", []operand{imm("NC"), imm("a16")}},
	{"ILLEGAL_D3", []operand{}},
	{"CALL", []operand{imm("NC"), imm("a16")}},
	{"PUSH", []operand{imm("DE")}},
	{"SUB", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$10")}},
	{"RET", []operand{imm("C")}},
	{"RETI", []operand{}},
	{"JP", []operand{imm("C"), imm("a16")}},
	{"ILLEGAL_DB", []operand{}},
	{"CALL", []operand{imm("C"), imm("a16")}},
	{"ILLEGAL_DD", []operand{}},
	{"SBC", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$18")}},
	{"LDH", []operand{reg("a8"), imm("A")}},
	{"POP", []operand{imm("HL")}},
	{"LD", []operand{reg("C"), imm("A")}},
	{"ILLEGAL_E3", []operand{}},
	{"ILLEGAL_E4", []operand{}},
	{"PUSH", []operand{imm("HL")}},
	{"AND", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$20")}},
	{"ADD", []operand{imm("SP"), imm("e8")}},
	{"JP", []operand{imm("HL")}},
	{"LD", []operand{reg("a16"), imm("A")}},
	{"ILLEGAL_EB", []operand{}},
	{"ILLEGAL_EC", []operand{}},
	{"ILLEGAL_ED", []operand{}},
	{"XOR", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$28")}},
	{"LDH", []operand{imm("A"), reg("a8")}},
	{"POP", []operand{imm("AF")}},
	{"LD", []operand{imm("A"), reg("C")}},
	{"DI", []operand{}},
	{"ILLEGAL_F4", []operand{}},
	{"PUSH", []operand{imm("AF")}},
	{"OR", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$30")}},
	{"LD", []operand{imm("HL"), imm("SP+"), imm("e8")}},
	{"LD", []operand{imm("SP"), imm("HL")}},
	{"LD", []operand{imm("A"), reg("a16")}},
	{"EI", []operand{}},
	{"ILLEGAL_FC", []operand{}},
	{"ILLEGAL_FD", []operand{}},
	{"CP", []operand{imm("A"), imm("n8")}},
	{"RST", []operand{imm("$38")}},
}

// cbOpcodeInfo provides a string representation of every CB opcode, used by the debugger.
var cbOpcodeInfo = []opcodeInformation{
	{"RLC", []operand{imm("B")}},
	{"RLC", []operand{imm("C")}},
	{"RLC", []operand{imm("D")}},
	{"RLC", []operand{imm("E")}},
	{"RLC", []operand{imm("H")}},
	{"RLC", []operand{imm("L")}},
	{"RLC", []operand{reg("HL")}},
	{"RLC", []operand{imm("A")}},
	{"RRC", []operand{imm("B")}},
	{"RRC", []operand{imm("C")}},
	{"RRC", []operand{imm("D")}},
	{"RRC", []operand{imm("E")}},
	{"RRC", []operand{imm("H")}},
	{"RRC", []operand{imm("L")}},
	{"RRC", []operand{reg("HL")}},
	{"RRC", []operand{imm("A")}},
	{"RL", []operand{imm("B")}},
	{"RL", []operand{imm("C")}},
	{"RL", []operand{imm("D")}},
	{"RL", []operand{imm("E")}},
	{"RL", []operand{imm("H")}},
	{"RL", []operand{imm("L")}},
	{"RL", []operand{reg("HL")}},
	{"RL", []operand{imm("A")}},
	{"RR", []operand{imm("B")}},
	{"RR", []operand{imm("C")}},
	{"RR", []operand{imm("D")}},
	{"RR", []operand{imm("E")}},
	{"RR", []operand{imm("H")}},
	{"RR", []operand{imm("L")}},
	{"RR", []operand{reg("HL")}},
	{"RR", []operand{imm("A")}},
	{"SLA", []operand{imm("B")}},
	{"SLA", []operand{imm("C")}},
	{"SLA", []operand{imm("D")}},
	{"SLA", []operand{imm("E")}},
	{"SLA", []operand{imm("H")}},
	{"SLA", []operand{imm("L")}},
	{"SLA", []operand{reg("HL")}},
	{"SLA", []operand{imm("A")}},
	{"SRA", []operand{imm("B")}},
	{"SRA", []operand{imm("C")}},
	{"SRA", []operand{imm("D")}},
	{"SRA", []operand{imm("E")}},
	{"SRA", []operand{imm("H")}},
	{"SRA", []operand{imm("L")}},
	{"SRA", []operand{reg("HL")}},
	{"SRA", []operand{imm("A")}},
	{"SWAP", []operand{imm("B")}},
	{"SWAP", []operand{imm("C")}},
	{"SWAP", []operand{imm("D")}},
	{"SWAP", []operand{imm("E")}},
	{"SWAP", []operand{imm("H")}},
	{"SWAP", []operand{imm("L")}},
	{"SWAP", []operand{reg("HL")}},
	{"SWAP", []operand{imm("A")}},
	{"SRL", []operand{imm("B")}},
	{"SRL", []operand{imm("C")}},
	{"SRL", []operand{imm("D")}},
	{"SRL", []operand{imm("E")}},
	{"SRL", []operand{imm("H")}},
	{"SRL", []operand{imm("L")}},
	{"SRL", []operand{reg("HL")}},
	{"SRL", []operand{imm("A")}},
	{"BIT", []operand{imm("0"), imm("B")}},
	{"BIT", []operand{imm("0"), imm("C")}},
	{"BIT", []operand{imm("0"), imm("D")}},
	{"BIT", []operand{imm("0"), imm("E")}},
	{"BIT", []operand{imm("0"), imm("H")}},
	{"BIT", []operand{imm("0"), imm("L")}},
	{"BIT", []operand{imm("0"), reg("HL")}},
	{"BIT", []operand{imm("0"), imm("A")}},
	{"BIT", []operand{imm("1"), imm("B")}},
	{"BIT", []operand{imm("1"), imm("C")}},
	{"BIT", []operand{imm("1"), imm("D")}},
	{"BIT", []operand{imm("1"), imm("E")}},
	{"BIT", []operand{imm("1"), imm("H")}},
	{"BIT", []operand{imm("1"), imm("L")}},
	{"BIT", []operand{imm("1"), reg("HL")}},
	{"BIT", []operand{imm("1"), imm("A")}},
	{"BIT", []operand{imm("2"), imm("B")}},
	{"BIT", []operand{imm("2"), imm("C")}},
	{"BIT", []operand{imm("2"), imm("D")}},
	{"BIT", []operand{imm("2"), imm("E")}},
	{"BIT", []operand{imm("2"), imm("H")}},
	{"BIT", []operand{imm("2"), imm("L")}},
	{"BIT", []operand{imm("2"), reg("HL")}},
	{"BIT", []operand{imm("2"), imm("A")}},
	{"BIT", []operand{imm("3"), imm("B")}},
	{"BIT", []operand{imm("3"), imm("C")}},
	{"BIT", []operand{imm("3"), imm("D")}},
	{"BIT", []operand{imm("3"), imm("E")}},
	{"BIT", []operand{imm("3"), imm("H")}},
	{"BIT", []operand{imm("3"), imm("L")}},
	{"BIT", []operand{imm("3"), reg("HL")}},
	{"BIT", []operand{imm("3"), imm("A")}},
	{"BIT", []operand{imm("4"), imm("B")}},
	{"BIT", []operand{imm("4"), imm("C")}},
	{"BIT", []operand{imm("4"), imm("D")}},
	{"BIT", []operand{imm("4"), imm("E")}},
	{"BIT", []operand{imm("4"), imm("H")}},
	{"BIT", []operand{imm("4"), imm("L")}},
	{"BIT", []operand{imm("4"), reg("HL")}},
	{"BIT", []operand{imm("4"), imm("A")}},
	{"BIT", []operand{imm("5"), imm("B")}},
	{"BIT", []operand{imm("5"), imm("C")}},
	{"BIT", []operand{imm("5"), imm("D")}},
	{"BIT", []operand{imm("5"), imm("E")}},
	{"BIT", []operand{imm("5"), imm("H")}},
	{"BIT", []operand{imm("5"), imm("L")}},
	{"BIT", []operand{imm("5"), reg("HL")}},
	{"BIT", []operand{imm("5"), imm("A")}},
	{"BIT", []operand{imm("6"), imm("B")}},
	{"BIT", []operand{imm("6"), imm("C")}},
	{"BIT", []operand{imm("6"), imm("D")}},
	{"BIT", []operand{imm("6"), imm("E")}},
	{"BIT", []operand{imm("6"), imm("H")}},
	{"BIT", []operand{imm("6"), imm("L")}},
	{"BIT", []operand{imm("6"), reg("HL")}},
	{"BIT", []operand{imm("6"), imm("A")}},
	{"BIT", []operand{imm("7"), imm("B")}},
	{"BIT", []operand{imm("7"), imm("C")}},
	{"BIT", []operand{imm("7"), imm("D")}},
	{"BIT", []operand{imm("7"), imm("E")}},
	{"BIT", []operand{imm("7"), imm("H")}},
	{"BIT", []operand{imm("7"), imm("L")}},
	{"BIT", []operand{imm("7"), reg("HL")}},
	{"BIT", []operand{imm("7"), imm("A")}},
	{"RES", []operand{imm("0"), imm("B")}},
	{"RES", []operand{imm("0"), imm("C")}},
	{"RES", []operand{imm("0"), imm("D")}},
	{"RES", []operand{imm("0"), imm("E")}},
	{"RES", []operand{imm("0"), imm("H")}},
	{"RES", []operand{imm("0"), imm("L")}},
	{"RES", []operand{imm("0"), reg("HL")}},
	{"RES", []operand{imm("0"), imm("A")}},
	{"RES", []operand{imm("1"), imm("B")}},
	{"RES", []operand{imm("1"), imm("C")}},
	{"RES", []operand{imm("1"), imm("D")}},
	{"RES", []operand{imm("1"), imm("E")}},
	{"RES", []operand{imm("1"), imm("H")}},
	{"RES", []operand{imm("1"), imm("L")}},
	{"RES", []operand{imm("1"), reg("HL")}},
	{"RES", []operand{imm("1"), imm("A")}},
	{"RES", []operand{imm("2"), imm("B")}},
	{"RES", []operand{imm("2"), imm("C")}},
	{"RES", []operand{imm("2"), imm("D")}},
	{"RES", []operand{imm("2"), imm("E")}},
	{"RES", []operand{imm("2"), imm("H")}},
	{"RES", []operand{imm("2"), imm("L")}},
	{"RES", []operand{imm("2"), reg("HL")}},
	{"RES", []operand{imm("2"), imm("A")}},
	{"RES", []operand{imm("3"), imm("B")}},
	{"RES", []operand{imm("3"), imm("C")}},
	{"RES", []operand{imm("3"), imm("D")}},
	{"RES", []operand{imm("3"), imm("E")}},
	{"RES", []operand{imm("3"), imm("H")}},
	{"RES", []operand{imm("3"), imm("L")}},
	{"RES", []operand{imm("3"), reg("HL")}},
	{"RES", []operand{imm("3"), imm("A")}},
	{"RES", []operand{imm("4"), imm("B")}},
	{"RES", []operand{imm("4"), imm("C")}},
	{"RES", []operand{imm("4"), imm("D")}},
	{"RES", []operand{imm("4"), imm("E")}},
	{"RES", []operand{imm("4"), imm("H")}},
	{"RES", []operand{imm("4"), imm("L")}},
	{"RES", []operand{imm("4"), reg("HL")}},
	{"RES", []operand{imm("4"), imm("A")}},
	{"RES", []operand{imm("5"), imm("B")}},
	{"RES", []operand{imm("5"), imm("C")}},
	{"RES", []operand{imm("5"), imm("D")}},
	{"RES", []operand{imm("5"), imm("E")}},
	{"RES", []operand{imm("5"), imm("H")}},
	{"RES", []operand{imm("5"), imm("L")}},
	{"RES", []operand{imm("5"), reg("HL")}},
	{"RES", []operand{imm("5"), imm("A")}},
	{"RES", []operand{imm("6"), imm("B")}},
	{"RES", []operand{imm("6"), imm("C")}},
	{"RES", []operand{imm("6"), imm("D")}},
	{"RES", []operand{imm("6"), imm("E")}},
	{"RES", []operand{imm("6"), imm("H")}},
	{"RES", []operand{imm("6"), imm("L")}},
	{"RES", []operand{imm("6"), reg("HL")}},
	{"RES", []operand{imm("6"), imm("A")}},
	{"RES", []operand{imm("7"), imm("B")}},
	{"RES", []operand{imm("7"), imm("C")}},
	{"RES", []operand{imm("7"), imm("D")}},
	{"RES", []operand{imm("7"), imm("E")}},
	{"RES", []operand{imm("7"), imm("H")}},
	{"RES", []operand{imm("7"), imm("L")}},
	{"RES", []operand{imm("7"), reg("HL")}},
	{"RES", []operand{imm("7"), imm("A")}},
	{"SET", []operand{imm("0"), imm("B")}},
	{"SET", []operand{imm("0"), imm("C")}},
	{"SET", []operand{imm("0"), imm("D")}},
	{"SET", []operand{imm("0"), imm("E")}},
	{"SET", []operand{imm("0"), imm("H")}},
	{"SET", []operand{imm("0"), imm("L")}},
	{"SET", []operand{imm("0"), reg("HL")}},
	{"SET", []operand{imm("0"), imm("A")}},
	{"SET", []operand{imm("1"), imm("B")}},
	{"SET", []operand{imm("1"), imm("C")}},
	{"SET", []operand{imm("1"), imm("D")}},
	{"SET", []operand{imm("1"), imm("E")}},
	{"SET", []operand{imm("1"), imm("H")}},
	{"SET", []operand{imm("1"), imm("L")}},
	{"SET", []operand{imm("1"), reg("HL")}},
	{"SET", []operand{imm("1"), imm("A")}},
	{"SET", []operand{imm("2"), imm("B")}},
	{"SET", []operand{imm("2"), imm("C")}},
	{"SET", []operand{imm("2"), imm("D")}},
	{"SET", []operand{imm("2"), imm("E")}},
	{"SET", []operand{imm("2"), imm("H")}},
	{"SET", []operand{imm("2"), imm("L")}},
	{"SET", []operand{imm("2"), reg("HL")}},
	{"SET", []operand{imm("2"), imm("A")}},
	{"SET", []operand{imm("3"), imm("B")}},
	{"SET", []operand{imm("3"), imm("C")}},
	{"SET", []operand{imm("3"), imm("D")}},
	{"SET", []operand{imm("3"), imm("E")}},
	{"SET", []operand{imm("3"), imm("H")}},
	{"SET", []operand{imm("3"), imm("L")}},
	{"SET", []operand{imm("3"), reg("HL")}},
	{"SET", []operand{imm("3"), imm("A")}},
	{"SET", []operand{imm("4"), imm("B")}},
	{"SET", []operand{imm("4"), imm("C")}},
	{"SET", []operand{imm("4"), imm("D")}},
	{"SET", []operand{imm("4"), imm("E")}},
	{"SET", []operand{imm("4"), imm("H")}},
	{"SET", []operand{imm("4"), imm("L")}},
	{"SET", []operand{imm("4"), reg("HL")}},
	{"SET", []operand{imm("4"), imm("A")}},
	{"SET", []operand{imm("5"), imm("B")}},
	{"SET", []operand{imm("5"), imm("C")}},
	{"SET", []operand{imm("5"), imm("D")}},
	{"SET", []operand{imm("5"), imm("E")}},
	{"SET", []operand{imm("5"), imm("H")}},
	{"SET", []operand{imm("5"), imm("L")}},
	{"SET", []operand{imm("5"), reg("HL")}},
	{"SET", []operand{imm("5"), imm("A")}},
	{"SET", []operand{imm("6"), imm("B")}},
	{"SET", []operand{imm("6"), imm("C")}},
	{"SET", []operand{imm("6"), imm("D")}},
	{"SET", []operand{imm("6"), imm("E")}},
	{"SET", []operand{imm("6"), imm("H")}},
	{"SET", []operand{imm("6"), imm("L")}},
	{"SET", []operand{imm("6"), reg("HL")}},
	{"SET", []operand{imm("6"), imm("A")}},
	{"SET", []operand{imm("7"), imm("B")}},
	{"SET", []operand{imm("7"), imm("C")}},
	{"SET", []operand{imm("7"), imm("D")}},
	{"SET", []operand{imm("7"), imm("E")}},
	{"SET", []operand{imm("7"), imm("H")}},
	{"SET", []operand{imm("7"), imm("L")}},
	{"SET", []operand{imm("7"), reg("HL")}},
	{"SET", []operand{imm("7"), imm("A")}},
}
